// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWyUi2XoysrpVIJimRoBYYr8jrigWkDmc',
    appId: '1:561467418674:web:138ce5b63809bc7ddc742b',
    messagingSenderId: '561467418674',
    projectId: 'civic-fix-93ac5',
    authDomain: 'civic-fix-93ac5.firebaseapp.com',
    storageBucket: 'civic-fix-93ac5.firebasestorage.app',
    measurementId: 'G-7G36FL1DY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMKHu-vo9XRGYMsIre2rnVmfLpOZnpPWQ',
    appId: '1:561467418674:android:ed18cbfeeedb6458dc742b',
    messagingSenderId: '561467418674',
    projectId: 'civic-fix-93ac5',
    storageBucket: 'civic-fix-93ac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8XmS_cdI_P-z8IkSpYw-3bPp74fx1XOw',
    appId: '1:561467418674:ios:86c566010372372edc742b',
    messagingSenderId: '561467418674',
    projectId: 'civic-fix-93ac5',
    storageBucket: 'civic-fix-93ac5.firebasestorage.app',
    iosBundleId: 'com.districtdirect.districtDirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8XmS_cdI_P-z8IkSpYw-3bPp74fx1XOw',
    appId: '1:561467418674:ios:86c566010372372edc742b',
    messagingSenderId: '561467418674',
    projectId: 'civic-fix-93ac5',
    storageBucket: 'civic-fix-93ac5.firebasestorage.app',
    iosBundleId: 'com.districtdirect.districtDirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWyUi2XoysrpVIJimRoBYYr8jrigWkDmc',
    appId: '1:561467418674:web:85b413fdbeb3a81edc742b',
    messagingSenderId: '561467418674',
    projectId: 'civic-fix-93ac5',
    authDomain: 'civic-fix-93ac5.firebaseapp.com',
    storageBucket: 'civic-fix-93ac5.firebasestorage.app',
    measurementId: 'G-TFWXYD68TP',
  );
}